[package]
name = "emojify-tg-sticker-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
color-eyre = "0.6.5"
emojify-tg-sticker = { path = "../lib" }
env_logger = "0.11.8"
image = "0.25.9"
log = { version = "0.4.29", features = ["std"] }
